sudo: false
language: go
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script:
    hugo server
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: public
    repo: whalecold/whalecold.github.io
    fqdn: <custom-domain-if-needed>
    target_branch: master
    email: zls1129@gmmail.com
    name: whalecold
